network:
  version: 2
  ethernets:
%{ if image == "debian12o" || image == "debian13o" || image == "amazonlinux2023o" || image == "ubuntu2404o" || image == "ubuntu2204o" || image == "slmicro62o" }
    ens3:
%{ else }
    eth0:
%{ endif }
      dhcp6: false
%{ if dhcp_dns }
      dhcp4: false
      addresses: ['${dhcp_dns_address}/24']
%{ else }
      dhcp4: true
%{ endif }
